# Generated by Django 6.0 on 2025-12-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_employee_id_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
