# Generated by Django 6.0 on 2025-12-24 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('site_code', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('category', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_tbl',
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved')], max_length=20)),
                ('action_notes', models.TextField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
            options={
                'db_table': 'document_reviews_tbl',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['current_status'], name='documents_t_current_fcc18a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_t_categor_9eab68_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['site_code'], name='documents_t_site_co_315e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by'], name='documents_t_created_f08a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['action'], name='document_re_action_c5e544_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['document'], name='document_re_documen_85cfe3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['action_by'], name='document_re_action__592e5a_idx'),
        ),
    ]
