# Generated by Django 5.2.9 on 2025-12-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_documentreview_document_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadeddocument",
            old_name="status",
            new_name="current_status",
        ),
    ]
