# Generated by Django 5.2.9 on 2025-12-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentaccesslog_documentversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='current_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
