# Generated by Django 5.2.9 on 2025-12-30 09:06
# Modified to handle data migration from text to ForeignKey

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_migrate_category_data'),
    ]

    operations = [
        # Step 1: Add new UUID columns for the ForeignKeys
        migrations.RunSQL(
            """
            ALTER TABLE dcs_documents ADD COLUMN IF NOT EXISTS category_id_new UUID;
            ALTER TABLE dcs_document_reviews ADD COLUMN IF NOT EXISTS old_category_id_new UUID;
            ALTER TABLE dcs_document_reviews ADD COLUMN IF NOT EXISTS new_category_id_new UUID;
            """,
            reverse_sql="""
            ALTER TABLE dcs_documents DROP COLUMN IF EXISTS category_id_new;
            ALTER TABLE dcs_document_reviews DROP COLUMN IF EXISTS old_category_id_new;
            ALTER TABLE dcs_document_reviews DROP COLUMN IF EXISTS new_category_id_new;
            """
        ),
        # Step 2: Populate new columns by joining with Category table
        migrations.RunSQL(
            """
            UPDATE dcs_documents d
            SET category_id_new = c.id
            FROM dcs_categories c
            WHERE d.category = c.category;
            
            UPDATE dcs_document_reviews dr
            SET old_category_id_new = c.id
            FROM dcs_categories c
            WHERE dr.old_category = c.category;
            
            UPDATE dcs_document_reviews dr
            SET new_category_id_new = c.id
            FROM dcs_categories c
            WHERE dr.new_category = c.category;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        # Step 3: Drop old text columns and rename new columns, then add foreign key constraints
        migrations.RunSQL(
            """
            ALTER TABLE dcs_documents 
            DROP COLUMN IF EXISTS category;
            
            ALTER TABLE dcs_documents 
            RENAME COLUMN category_id_new TO category_id;
            
            ALTER TABLE dcs_document_reviews 
            DROP COLUMN IF EXISTS old_category;
            
            ALTER TABLE dcs_document_reviews 
            DROP COLUMN IF EXISTS new_category;
            
            ALTER TABLE dcs_document_reviews 
            RENAME COLUMN old_category_id_new TO old_category_id;
            
            ALTER TABLE dcs_document_reviews 
            RENAME COLUMN new_category_id_new TO new_category_id;
            
            -- Add foreign key constraints
            ALTER TABLE dcs_documents 
            ADD CONSTRAINT dcs_documents_category_id_fk 
            FOREIGN KEY (category_id) REFERENCES dcs_categories(id) ON DELETE SET NULL;
            
            ALTER TABLE dcs_document_reviews 
            ADD CONSTRAINT dcs_document_reviews_old_category_id_fk 
            FOREIGN KEY (old_category_id) REFERENCES dcs_categories(id) ON DELETE SET NULL;
            
            ALTER TABLE dcs_document_reviews 
            ADD CONSTRAINT dcs_document_reviews_new_category_id_fk 
            FOREIGN KEY (new_category_id) REFERENCES dcs_categories(id) ON DELETE SET NULL;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        # Step 4: Update Django model state to reflect ForeignKey fields
        # Use SeparateDatabaseAndState since we've already handled the database changes
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database is already updated via RunSQL above, so no-op here
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='documentaudit',
                    name='new_category',
                ),
                migrations.RemoveField(
                    model_name='documentaudit',
                    name='old_category',
                ),
                migrations.RemoveField(
                    model_name='uploadeddocument',
                    name='category',
                ),
                migrations.AddField(
                    model_name='documentaudit',
                    name='new_category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_category_audits', to='documents.category'),
                ),
                migrations.AddField(
                    model_name='documentaudit',
                    name='old_category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_category_audits', to='documents.category'),
                ),
                migrations.AddField(
                    model_name='uploadeddocument',
                    name='category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.category'),
                ),
            ]
        ),
    ]
