# Generated by Django 5.2.9 on 2026-01-01 06:18
# Modified to handle case where project_code column doesn't exist

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_projectcode'),
    ]

    operations = [
        # Step 1: Create ProjectCode records from existing text values (if column exists)
        migrations.RunSQL(
            """
            -- Create ProjectCode records from existing project_code text values
            DO $$
            DECLARE
                project_code_text TEXT;
                user_id UUID;
                project_code_id UUID;
            BEGIN
                -- Check if project_code column exists as text
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'dcs_documents' 
                    AND column_name = 'project_code'
                    AND data_type = 'character varying'
                ) THEN
                    -- Get a default user for creating ProjectCode records
                    SELECT id INTO user_id FROM auth_user WHERE is_superuser = TRUE LIMIT 1;
                    IF user_id IS NULL THEN
                        SELECT id INTO user_id FROM auth_user LIMIT 1;
                    END IF;
                    
                    -- Create ProjectCode records for each unique project_code value
                    FOR project_code_text IN 
                        SELECT DISTINCT project_code 
                        FROM dcs_documents 
                        WHERE project_code IS NOT NULL AND project_code != ''
                    LOOP
                        -- Check if ProjectCode already exists
                        SELECT id INTO project_code_id 
                        FROM dcs_project_codes 
                        WHERE project_code = project_code_text;
                        
                        -- Create if doesn't exist
                        IF project_code_id IS NULL AND user_id IS NOT NULL THEN
                            INSERT INTO dcs_project_codes (id, project_code, is_active, created_datetime, updated_datetime, created_by_id)
                            VALUES (gen_random_uuid(), project_code_text, TRUE, NOW(), NOW(), user_id);
                        END IF;
                    END LOOP;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        # Step 2: Convert project_code column from text to ForeignKey
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    -- Check if project_code column exists and handle accordingly
                    DO $$
                    BEGIN
                        -- If column exists as text, migrate it
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'dcs_documents' 
                            AND column_name = 'project_code'
                            AND data_type = 'character varying'
                        ) THEN
                            -- Add temporary UUID column
                            ALTER TABLE dcs_documents ADD COLUMN IF NOT EXISTS project_code_id_new UUID;
                            
                            -- Populate new column by joining with ProjectCode table
                            UPDATE dcs_documents d
                            SET project_code_id_new = pc.id
                            FROM dcs_project_codes pc
                            WHERE d.project_code = pc.project_code;
                            
                            -- Drop old text column
                            ALTER TABLE dcs_documents DROP COLUMN IF EXISTS project_code;
                            
                            -- Rename new column
                            ALTER TABLE dcs_documents RENAME COLUMN project_code_id_new TO project_code_id;
                            
                            -- Add foreign key constraint
                            ALTER TABLE dcs_documents 
                            ADD CONSTRAINT dcs_documents_project_code_id_fk 
                            FOREIGN KEY (project_code_id) REFERENCES dcs_project_codes(id) ON DELETE SET NULL;
                        ELSE
                            -- If column doesn't exist, add it as ForeignKey directly
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'dcs_documents' 
                                AND column_name = 'project_code_id'
                            ) THEN
                                ALTER TABLE dcs_documents ADD COLUMN project_code_id UUID;
                                
                                ALTER TABLE dcs_documents 
                                ADD CONSTRAINT dcs_documents_project_code_id_fk 
                                FOREIGN KEY (project_code_id) REFERENCES dcs_project_codes(id) ON DELETE SET NULL;
                            END IF;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop
                ),
            ],
            state_operations=[
                # Update Django model state
                migrations.RemoveField(
                    model_name='uploadeddocument',
                    name='project_code',
                ),
                migrations.AddField(
                    model_name='uploadeddocument',
                    name='project_code',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.projectcode'),
                ),
            ]
        ),
    ]
