# Generated by Django 5.2.9 on 2026-01-01 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_projectcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.projectcode'),
        ),
    ]
